### ISSUE TITLE
Copy from list action not copying from given named list

### ISSUE THREAD

**Issue by ClicksEnStock** [LB--/InternalList-Object#2]
In action_copy_items_from_list:
string_view_t const list_from_name = reinterpret_cast<char_t const *>(CNC_GetStringParameter(run_data));
...
auto const *const list_from_ptr = run_data->current_optional();

list_from_name is not used to set list retrieved with run_data->current_optional()

**Comment by LB--** [comment]
Thanks! Fixed in https://github.com/LB--/InternalList-Object/releases/tag/v2.0.1
